# Reusable GitHub Actions workflow: Publish to NPM
# Publishes the NPM Package

name: Custom Timeout

on:
  workflow_call:
    inputs:
      timeout_minutes:
        type: number
        required: false
        default: 10
        description: Custom Timeout in Minutes

jobs:
  test-custom-timeout:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout_minutes }}

    steps:
      # STEP 1: Validate the package manager input
      - name: Sleep for 10 mins
        id: sleep
        run: |
          echo "sleeping for 10 minutes"
          sleep 300

      # STEP 2: Checkout the repository code
      - name: Done
        run: |
          echo "Completed Testing"
